### ISSUE TITLE
'user' is reserved keyword in postgresql

### ISSUE THREAD

**Issue by Ovascos** [SymfonyCasts/symfony-ux#12]
Hi :wave:

when setting up the project using a PostgreSQL database, loading the fixtures fails as "user" is a reserved keyword in PostgreSQL. Unfortunately, this conflicts with the User entity. 
As Doctrine is not providing escaping of table names, manual escaping e.g. using ```@ORM\Table(name="`user`")``` in Entity/User.php is required.

**Comment by MolloKhan** [comment]
Hey @Ovascos 

That's interesting. Doctrine is smart enough to detect the `user` keyword for MySQL but not for PostgreSQL. I wonder if Doctrine fixed it in a recent version, but anyway, thanks for reporting it :)

**Comment by MolloKhan** [comment]
I just updated the tutorial. Thank you @Ovascos!

**Comment by Ovascos** [comment]
Hi @MolloKhan 

According to Doctrine documentation, not escaping column and table names is by design: https://www.doctrine-project.org/projects/doctrine-orm/en/2.13/reference/basic-mapping.html#quoting-reserved-words
Don't know why it's working for MySQL.

Anyway, thanks a lot for the speedy fix!

**Comment by MolloKhan** [comment]
Thanks for the link. I don't know why it works for MySQL neither 😅
