### ISSUE TITLE
Wrong React component name

### ISSUE THREAD

**Issue by t-richard** [SymfonyCasts/symfony-ux#2]
Hi :wave: 

I feel like these code samples from [this chapter](https://symfonycasts.com/screencast/stimulus/react-props#rendering-the-new-component) have a wrong React component name : 
* https://github.com/SymfonyCasts/symfony-ux/blob/33b46261c295248c9350cc9a641f2cd6502beaec/_tuts/reactprops-add-controller.diff#L15
* https://github.com/SymfonyCasts/symfony-ux/blob/33b46261c295248c9350cc9a641f2cd6502beaec/_tuts/reactprops-manually-pass-prop.diff#L16

If I understand correctly, it should be `FeaturedProduct` instead of `FeatureProduct`.

Let me know what you think.

**Comment by larzuk91** [comment]
Hey @t-richard you're right, the code blocks have a flaw. Thanks for reporting it, I'll make it fix :)
Thanks!
